language: java
env:
  - secure: "Tql2hC1Cd8Ewjb2xCI5k43QriUbaCQMg0ahCCWK2N3x9gCdRx61OXk5qOxjEXjyvB4cr08HK4CajiGPqymKYapdlrwwvFGJoRjQAW4GMxto75tXlls13XWICYAoI5M9rXcicZJFfXr9D33hasE3NvqauzszdIs6DKGPzlikWYvAMJ8Ev7zBVget6g8vLa3FW+5VYa/85M0T92BTXpkA/VKs81LHcx/EBSmvLRjYveSrj3jP1r8uwYz4skT2DnTF5r6Uk/fqWQhiSlzEkoBz4gl4SEoTJ5PS4Fq13e/IsE/i/CxkdBCESw8oFmBqAq2sWD3/rg9/5gGaZc2BFukxZWmfaFtT/d5Q2i3+XmeVJBzBsb2XbQn122aIACkICF3NJsW7T4F+WLU2eeVZJF94jyBEKhus1eV+W+MJoRAIMzXi2SNADVs4eZbu8Lse2T05bEY7Bsx4VpEmHYMdJ66615TD30AbLnyeyNhe6buFm+x7ZPXp/s/E+UcfMDV/IP4OB+4lBJwim67aqXZ5VMej5RXog+ca2IKEFiZphHC/NnTJLagktIIHPcRW23/iC18ztBTxPhmdHs2Qf/z2ULtujk3H+kljmN6xlw0W5hw1UkwROdwUsEsZFFp2OT3lAPq2U/1rmbVfxiim2VYbJw0ISvUqIgrMG29dN2DjiozVJac8="
install: true
script: ./gradlew build
deploy:
  provider: script
  script: ./gradlew publish
  on:
    branch: master